version: '3.8'

services:
  redis:
    image: 'redis:latest'
    container_name: 'redis-server'
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

  weaviate:
    image: 'semitechnologies/weaviate:1.25.0'
    container_name: 'weaviate-server'
    ports:
      - '8080:8080'
      - '50051:50051'
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      ENABLE_MODULES: 'text2vec-transformers'
      CLUSTER_HOSTNAME: 'node1'
    volumes:
      - weaviate_data:/var/lib/weaviate
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/v1/.well-known/ready"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  redis_data:
    driver: local
  weaviate_data:
    driver: local 